# Generated by Django 4.2.2 on 2023-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0002_alter_exerciseset_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='intensity',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=1, max_length=50),
        ),
    ]
