# Generated by Django 4.2.2 on 2023-08-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0003_exerciseset_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='intensity',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default=1, max_length=50),
        ),
    ]
