# Generated by Django 4.2.2 on 2023-09-01 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrack', '0005_proteincal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.CharField(choices=[('Sedentary', 'Sedentary: little or no exercise'), ('Light', 'Light: exercise 1-3 times/week'), ('Moderate', 'Moderate: exercise 4-5 times/week'), ('Active', 'Active: daily exercise or intense exercise 3-4 times/week'), ('VeryActive', 'Very Active: intense exercise 6-7 times/week'), ('ExtraActive', 'Extra Active: very intense exercise daily, or physical job')], default='Sedentary', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
